fruits=["peach","banana","apple","orange"]
print(fruits)
fruits.append("blueberris")
print(fruits)
fruits.insert(2,"strawberry")
print (fruits)
fruits.remove("peach")
print(fruits)
fruits.reverse()
print(fruits)
fruits.pop(1)
print(fruits[3])
fruits.sort()
print(fruits)
